---
- import_tasks: "dependencies.yml"

- import_tasks: "lego.yml"

- import_tasks: "csr.yml"

- name: "Create Certificates"
  include_tasks: "certificate.yml"
  with_items: "{{ lets_encrypt_resources }}"
  loop_control:
      loop_var: "lets_encrypt_resource"

- import_tasks: "cron.yml"

- import_tasks: "add-staging-as-trusted.yml"
  when: lets_encrypt_install_as_trusted